# Generated by Django 3.2.7 on 2021-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=20)),
                ('empName', models.CharField(max_length=100)),
                ('empEmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('empAddress', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
